export const globalsTemplate = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: light dark;
}

body {
  font-family: Inter, Arial, sans-serif;
}
`;

export const nextConfigTemplate = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true
};

export default nextConfig;
`;

export const tailwindConfigTemplate = `import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {}
  },
  plugins: []
};

export default config;
`;

export const postcssTemplate = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
};
`;

export const packageJsonTemplate = `{
  "name": "web-preview",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "15.3.1",
    "react": "19.1.0",
    "react-dom": "19.1.0"
  },
  "devDependencies": {
    "typescript": "5.8.3",
    "tailwindcss": "3.4.17",
    "postcss": "8.5.3",
    "autoprefixer": "10.4.21",
    "@types/react": "19.1.2",
    "@types/react-dom": "19.1.2",
    "@types/node": "22.15.3"
  }
}
`;

export const tsconfigTemplate = `${JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      strict: true,
      noEmit: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      baseUrl: '.',
      paths: {
        '@/*': ['./*']
      }
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules']
  },
  null,
  2
)}\n`;

export const nextEnvTemplate = `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js
`;
